
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bohacikj
 */
public class AplikaciaGUIUkazky extends javax.swing.JFrame {

    /**
     * Creates new form AplikaciaGUIUkazky
     */
    public AplikaciaGUIUkazky() {
        initComponents();
        
        try {
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        }catch(Exception e){
            System.out.println("Nepodporovany look and feel.");
        }
        
        grpFarby.add(rbtCervena);
        grpFarby.add(rbtZelena);
        grpFarby.add(rbtModra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        grpFarby = new javax.swing.ButtonGroup();
        btnOK = new javax.swing.JButton();
        txtMenoAPriezvisko = new javax.swing.JTextField();
        lblMenoAPriezvisko = new javax.swing.JLabel();
        btnZobrazMenoAPriezvisko = new javax.swing.JButton();
        cbxPosielatReklamu = new javax.swing.JCheckBox();
        btnInfoOReklame = new javax.swing.JButton();
        rbtCervena = new javax.swing.JRadioButton();
        rbtZelena = new javax.swing.JRadioButton();
        rbtModra = new javax.swing.JRadioButton();
        btnZvolenaFarba = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpVysledky = new javax.swing.JTextPane();
        menuProgramu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        koniecProgramu = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mysVoslaNaTlacitkoOK(evt);
            }
        });
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblMenoAPriezvisko.setText("Meno a preizvisko:");

        btnZobrazMenoAPriezvisko.setText("Zobraz");
        btnZobrazMenoAPriezvisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZobrazMenoAPriezviskoActionPerformed(evt);
            }
        });

        cbxPosielatReklamu.setSelected(true);
        cbxPosielatReklamu.setText("Posielat reklamu");

        btnInfoOReklame.setText("Info o reklame");
        btnInfoOReklame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoOReklameActionPerformed(evt);
            }
        });

        rbtCervena.setText("Cervena");

        rbtZelena.setSelected(true);
        rbtZelena.setText("Zelena");

        rbtModra.setText("Modra");

        btnZvolenaFarba.setText("Zvolena farba");
        btnZvolenaFarba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZvolenaFarbaActionPerformed(evt);
            }
        });

        txpVysledky.setEditable(false);
        jScrollPane1.setViewportView(txpVysledky);

        jMenu1.setText("Program");

        koniecProgramu.setText("Koniec");
        koniecProgramu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koniecProgramuActionPerformed(evt);
            }
        });
        jMenu1.add(koniecProgramu);

        menuProgramu.add(jMenu1);

        setJMenuBar(menuProgramu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
                    .addComponent(rbtModra)
                    .addComponent(rbtCervena)
                    .addComponent(lblMenoAPriezvisko)
                    .addComponent(btnOK)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMenoAPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPosielatReklamu)
                            .addComponent(rbtZelena))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnZvolenaFarba)
                            .addComponent(btnInfoOReklame)
                            .addComponent(btnZobrazMenoAPriezvisko))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnOK)
                .addGap(28, 28, 28)
                .addComponent(lblMenoAPriezvisko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMenoAPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZobrazMenoAPriezvisko))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPosielatReklamu)
                    .addComponent(btnInfoOReklame))
                .addGap(23, 23, 23)
                .addComponent(rbtCervena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtZelena)
                    .addComponent(btnZvolenaFarba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtModra)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Bolo stlacene tlacitko OK.");
    }//GEN-LAST:event_btnOKActionPerformed

    private void mysVoslaNaTlacitkoOK(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mysVoslaNaTlacitkoOK
        // TODO add your handling code here:
        System.out.println(evt.getX());
        System.out.println(evt.getY());
    }//GEN-LAST:event_mysVoslaNaTlacitkoOK

    private void koniecProgramuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koniecProgramuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_koniecProgramuActionPerformed

    private void btnZobrazMenoAPriezviskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZobrazMenoAPriezviskoActionPerformed
        // TODO add your handling code here:
        
        String menoAPriezvisko = txtMenoAPriezvisko.getText();
        
        JOptionPane.showMessageDialog(this, "Bolo zadane nasledovne meno a priezvisko: " +
                menoAPriezvisko);
    }//GEN-LAST:event_btnZobrazMenoAPriezviskoActionPerformed

    private void btnInfoOReklameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoOReklameActionPerformed
        // TODO add your handling code here:
        
        String pom = "nebude";
        if(cbxPosielatReklamu.isSelected()){
            pom = "bude";
        }
        
        JOptionPane.showMessageDialog(this, "Reklama sa " + pom + " posielat.");
    }//GEN-LAST:event_btnInfoOReklameActionPerformed

    private void btnZvolenaFarbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZvolenaFarbaActionPerformed
        // TODO add your handling code here:
        String pom="";
        if(rbtCervena.isSelected()){
            pom = "cervena";
        }
        if(rbtZelena.isSelected()){
            pom = "zelena";
        }
        if(rbtModra.isSelected()){
            pom = "modra";
        }
        
        
        String vysl = "Zvolena je " + pom + " farba.";
        if(txpVysledky.getText().equals("")){
            txpVysledky.setText(vysl);
        }else{
            txpVysledky.setText(txpVysledky.getText() + "\n" + vysl);
        }
    }//GEN-LAST:event_btnZvolenaFarbaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikaciaGUIUkazky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikaciaGUIUkazky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikaciaGUIUkazky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikaciaGUIUkazky.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikaciaGUIUkazky().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfoOReklame;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnZobrazMenoAPriezvisko;
    private javax.swing.JButton btnZvolenaFarba;
    private javax.swing.JCheckBox cbxPosielatReklamu;
    private javax.swing.ButtonGroup grpFarby;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem koniecProgramu;
    private javax.swing.JLabel lblMenoAPriezvisko;
    private javax.swing.JMenuBar menuProgramu;
    private javax.swing.JRadioButton rbtCervena;
    private javax.swing.JRadioButton rbtModra;
    private javax.swing.JRadioButton rbtZelena;
    private javax.swing.JTextPane txpVysledky;
    private javax.swing.JTextField txtMenoAPriezvisko;
    // End of variables declaration//GEN-END:variables
}
