package dialogy;

import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bohacikj
 */
public class NovyNakladnyPriestor extends javax.swing.JDialog {
    private JDialog dialog;
    private HashMap<String,Object> preberaneUdaje;
    
    /**
     * Creates new form NovyNakladAnyPriestor
     */
    public NovyNakladnyPriestor(java.awt.Frame parent, boolean modal, 
                HashMap<String,Object> preberaneUdaje) {
        super(parent, modal);
        initComponents();
        
        try {
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        }catch(Exception e){
            System.out.println("Nepodporovany look and feel.");
        }
        
        dialog = this;
        
        preberaneUdaje.put("chyba", "true");
        
        this.preberaneUdaje = preberaneUdaje;
        
        cbxMaxPocetKrokodilov.setSelectedItem("3");
        cbxMaxPocetPracovnikov.setSelectedItem("10");
        cbxMaxHmotnost.setSelectedItem("1000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxMaxPocetKrokodilov = new javax.swing.JComboBox<>();
        lblMaxPocetKrokodilov = new javax.swing.JLabel();
        lblMaxPocetPracovnikov = new javax.swing.JLabel();
        cbxMaxPocetPracovnikov = new javax.swing.JComboBox<>();
        lblMaxHmotnost = new javax.swing.JLabel();
        cbxMaxHmotnost = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxMaxPocetKrokodilov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "20", "30", "40", "50", "100", "500", "1000" }));
        cbxMaxPocetKrokodilov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaxPocetKrokodilovActionPerformed(evt);
            }
        });

        lblMaxPocetKrokodilov.setText("Maximalny pocet krokodilov:");

        lblMaxPocetPracovnikov.setText("Maximalny pocet pracovnikov:");

        cbxMaxPocetPracovnikov.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "20", "30", "40", "50", "100", "500", "1000" }));

        lblMaxHmotnost.setText("Maximalna hmotnost:");

        cbxMaxHmotnost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "500", "1000", "2000", "3000", "4000", "5000", "10000", "50000" }));
        cbxMaxHmotnost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMaxHmotnostActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaxPocetKrokodilov)
                    .addComponent(lblMaxPocetPracovnikov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxMaxPocetPracovnikov, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxMaxPocetKrokodilov, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMaxHmotnost)
                    .addComponent(cbxMaxHmotnost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaxPocetKrokodilov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMaxPocetKrokodilov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaxPocetPracovnikov)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMaxPocetPracovnikov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaxHmotnost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMaxHmotnost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMaxPocetKrokodilovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaxPocetKrokodilovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaxPocetKrokodilovActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        preberaneUdaje.put("maxPocetKrokodilov",
                new Integer(Integer.parseInt((String)cbxMaxPocetKrokodilov.getSelectedItem())));
        preberaneUdaje.put("maxPocetPracovnikov",
                new Integer(Integer.parseInt((String)cbxMaxPocetPracovnikov.getSelectedItem())));
        preberaneUdaje.put("maxHmotnost",
                new Double(Double.parseDouble((String)cbxMaxHmotnost.getSelectedItem())));                
        
        preberaneUdaje.put("chyba", "false");
        
        dialog.setVisible(false);
        
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbxMaxHmotnostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMaxHmotnostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMaxHmotnostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovyNakladnyPriestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovyNakladnyPriestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovyNakladnyPriestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovyNakladnyPriestor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        HashMap<String,Object> preberaneUdaje = new HashMap<String,Object>();
        
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NovyNakladnyPriestor dialog = new NovyNakladnyPriestor(
                        new javax.swing.JFrame(), true, preberaneUdaje);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbxMaxHmotnost;
    private javax.swing.JComboBox<String> cbxMaxPocetKrokodilov;
    private javax.swing.JComboBox<String> cbxMaxPocetPracovnikov;
    private javax.swing.JLabel lblMaxHmotnost;
    private javax.swing.JLabel lblMaxPocetKrokodilov;
    private javax.swing.JLabel lblMaxPocetPracovnikov;
    // End of variables declaration//GEN-END:variables
}
