/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialogy;

import java.util.HashMap;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.JDialog;

/**
 *
 * @author prochazka6
 */
public class PridajRuru extends javax.swing.JDialog {
    
    private JDialog dialog;
    private HashMap<String, Object> preberaneUdaje;

    /**
     * Creates new form PridajRuru
     */
    public PridajRuru(java.awt.Frame parent, boolean modal, HashMap<String,Object> preberaneUdaje) {
        super(parent, modal);
        initComponents();
        
        try {
            //UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        }catch(Exception e){
            System.out.println("Nepodporovany look and feel.");
        }
        
        dialog = this;
        
        preberaneUdaje.put("Chyba", "true");
        
        this.preberaneUdaje = preberaneUdaje;
        
        cbxHmotnost.setSelectedItem("3");//nastavi defaultnu hmotnost
      /*  
  
        
        cbxMaxPocetKrokodilov.setSelectedItem("3");
        cbxMaxPocetPracovnikov.setSelectedItem("10");
        cbxMaxHmotnost.setSelectedItem("1000"); */
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxHmotnost = new javax.swing.JComboBox<>();
        cbxDlzka = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        jlEvidencneCislo = new javax.swing.JLabel();
        txfEvidencneCislo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblDlzka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbxHmotnost.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1", "5", "2", "2.5", "3", "3.5", "4", "4.5", "5", "5.5 6", "7", "8", "9", "10" }));

        cbxDlzka.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5", " ", " " }));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jlEvidencneCislo.setText("Evidencne cislo:");

        txfEvidencneCislo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfEvidencneCisloActionPerformed(evt);
            }
        });

        jLabel2.setText("Hmotnost (kg):");

        lblDlzka.setText("Dlzka (m):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlEvidencneCislo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblDlzka)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK))
                    .addComponent(cbxDlzka, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxHmotnost, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfEvidencneCislo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jlEvidencneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfEvidencneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxHmotnost, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDlzka)
                .addGap(4, 4, 4)
                .addComponent(cbxDlzka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfEvidencneCisloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfEvidencneCisloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfEvidencneCisloActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        
        preberaneUdaje.put("evidencneCislo",txfEvidencneCislo.getText());
        preberaneUdaje.put("hmotnost", 
               new Double (Double.parseDouble((String)cbxHmotnost.getSelectedItem())));
        preberaneUdaje.put("dlzlka", 
               new Double (Double.parseDouble((String)cbxDlzka.getSelectedItem())));
                              
        preberaneUdaje.put("chyba", "false");
        
        dialog.setVisible(false);
    
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridajRuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridajRuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridajRuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridajRuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        HashMap<String,Object> preberaneUdaje = new HashMap<String, Object>();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridajRuru dialog = new PridajRuru(new javax.swing.JFrame(), true, preberaneUdaje);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbxDlzka;
    private javax.swing.JComboBox<String> cbxHmotnost;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlEvidencneCislo;
    private javax.swing.JLabel lblDlzka;
    private javax.swing.JTextField txfEvidencneCislo;
    // End of variables declaration//GEN-END:variables
}
